### ISSUE TITLE
Use haversine formula instead of manhatton

### ISSUE THREAD

**Issue by vianneynara** [lusbnz/osm-astar#1]
This project did a great job of implementing the algorithm, but why does it use Manhattan formula to calculate between 2 points? The earth is round, basically a sphere, so using [Haversine](https://en.wikipedia.org/wiki/Haversine_formula) would fit best to find distances between two points.

**Comment by lusbnz** [comment]
We appreciate your feedback. In fact, we created this project for use in the Introduction to Artificial Intelligence course, which requires calculating distances and finding the shortest path using two specific 2D distance metrics: Euclidean and Manhattan. We will take your suggestion into consideration for future updates. 

Thank you very much!
